use_frameworks!

platform :ios, '9.0'

target 'YIMios_Example' do
  pod 'YIMios', :path => '../'
  
  pod 'IQKeyboardManager'

  target 'YIMios_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
