use_frameworks!

platform :ios, '9.0'

target 'YIMios_Example' do
  pod 'YIMios', :path => '../'
  pod 'SDWebImage'
  pod 'AFNetworking','~> 3.2.1'
  pod 'SVProgressHUD'
#  pod 'IQKeyboardManager'

  target 'YIMios_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
